import {
  Bot,
  Sparkles,
  BrainCircuit,
  ShieldCheck,
} from "lucide-react";

interface Props {
  summary: {
    summary: string;
    confidence: number;
    recommendation: string;
  };
}

export default function InventorySummary({
  summary,
}: Props) {
  return (
    <div className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-900 shadow-xl">

      {/* Header */}

      <div className="flex items-center justify-between border-b border-slate-800 px-8 py-6">

        <div className="flex items-center gap-4">

          <div className="rounded-2xl bg-gradient-to-br from-indigo-600 to-blue-600 p-4">

            <Bot
              className="text-white"
              size={24}
            />

          </div>

          <div>

            <h2 className="text-2xl font-bold text-white">
              AI Inventory Insights
            </h2>

            <p className="mt-1 text-slate-400">
              Executive summary generated by GrowthPilot AI
            </p>

          </div>

        </div>

        <div className="rounded-xl bg-indigo-500/10 px-5 py-3">

          <div className="flex items-center gap-2">

            <Sparkles
              className="text-indigo-400"
              size={18}
            />

            <span className="font-semibold text-indigo-400">
              AI Analysis
            </span>

          </div>

        </div>

      </div>

      {/* Summary */}

      <div className="p-8">

        <div className="rounded-2xl border border-slate-800 bg-slate-950 p-6">

          <div className="flex items-center gap-3 mb-4">

            <BrainCircuit
              className="text-blue-400"
              size={22}
            />

            <h3 className="text-xl font-semibold text-white">
              Executive Summary
            </h3>

          </div>

          <p className="leading-8 text-slate-300">
            {summary.summary}
          </p>

        </div>

        {/* KPI */}

        <div className="mt-8 grid gap-6 md:grid-cols-2">

          <div className="rounded-2xl bg-slate-800 p-6">

            <p className="text-slate-400">
              AI Confidence
            </p>

            <h2 className="mt-3 text-5xl font-bold text-green-400">
              {summary.confidence}%
            </h2>

            <div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-700">

              <div
                className="h-full rounded-full bg-gradient-to-r from-green-500 to-emerald-400"
                style={{
                  width: `${summary.confidence}%`,
                }}
              />

            </div>

          </div>

          <div className="rounded-2xl bg-slate-800 p-6">

            <div className="flex items-center gap-3">

              <ShieldCheck
                className="text-yellow-400"
                size={22}
              />

              <h3 className="text-lg font-semibold text-white">
                Recommendation
              </h3>

            </div>

            <p className="mt-4 leading-7 text-slate-300">
              {summary.recommendation}
            </p>

          </div>

        </div>

      </div>

    </div>
  );
}