import {
  Bot,
  Sparkles,
  BrainCircuit,
  ShieldCheck,
  TrendingUp,
} from "lucide-react";

interface Props {
  insights: {
    summary: string;
    confidence: number;
    recommendation: string;
    top_customer?: string;
    retention_rate?: number;
  };
}

export default function CustomerInsights({
  insights,
}: Props) {
  return (
    <div className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-900 shadow-xl">

      {/* Header */}

      <div className="flex items-center justify-between border-b border-slate-800 px-8 py-6">

        <div className="flex items-center gap-4">

          <div className="rounded-2xl bg-gradient-to-br from-indigo-600 to-blue-600 p-4 shadow-lg">

            <Bot
              className="text-white"
              size={24}
            />

          </div>

          <div>

            <h2 className="text-2xl font-bold text-white">
              AI Customer Insights
            </h2>

            <p className="mt-1 text-slate-400">
              Generated by GrowthPilot AI
            </p>

          </div>

        </div>

        <div className="rounded-xl bg-indigo-500/10 px-5 py-3">

          <div className="flex items-center gap-2">

            <Sparkles
              className="text-indigo-400"
              size={18}
            />

            <span className="font-semibold text-indigo-400">
              AI Powered
            </span>

          </div>

        </div>

      </div>

      <div className="p-8">

        {/* Summary */}

        <div className="rounded-2xl border border-slate-800 bg-slate-950 p-6">

          <div className="mb-4 flex items-center gap-3">

            <BrainCircuit
              className="text-blue-400"
              size={22}
            />

            <h3 className="text-xl font-semibold text-white">
              Executive Summary
            </h3>

          </div>

          <p className="leading-8 text-slate-300">
            {insights.summary}
          </p>

        </div>

        {/* Analytics */}

        <div className="mt-8 grid gap-6 md:grid-cols-2">

          {/* Confidence */}

          <div className="rounded-2xl bg-slate-800 p-6">

            <div className="flex items-center gap-3">

              <TrendingUp
                className="text-green-400"
                size={22}
              />

              <h3 className="text-lg font-semibold text-white">
                AI Confidence
              </h3>

            </div>

            <h2 className="mt-5 text-5xl font-bold text-green-400">
              {insights.confidence}%
            </h2>

            <div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-700">

              <div
                className="h-full rounded-full bg-gradient-to-r from-green-500 to-emerald-400"
                style={{
                  width: `${insights.confidence}%`,
                }}
              />

            </div>

          </div>

          {/* Recommendation */}

          <div className="rounded-2xl bg-slate-800 p-6">

            <div className="flex items-center gap-3">

              <ShieldCheck
                className="text-yellow-400"
                size={22}
              />

              <h3 className="text-lg font-semibold text-white">
                AI Recommendation
              </h3>

            </div>

            <p className="mt-5 leading-7 text-slate-300">
              {insights.recommendation}
            </p>

          </div>

        </div>

        {/* Extra Stats */}

        <div className="mt-8 grid gap-6 lg:grid-cols-2">

          <div className="rounded-2xl border border-slate-800 bg-slate-950 p-6">

            <p className="text-slate-400">
              Top Customer
            </p>

            <h3 className="mt-3 text-2xl font-bold text-white">
              {insights.top_customer ?? "N/A"}
            </h3>

          </div>

          <div className="rounded-2xl border border-slate-800 bg-slate-950 p-6">

            <p className="text-slate-400">
              Retention Rate
            </p>

            <h3 className="mt-3 text-2xl font-bold text-blue-400">
              {insights.retention_rate ?? "--"}%
            </h3>

          </div>

        </div>

      </div>

    </div>
  );
}