import { AlertTriangle, Package, TrendingUp } from "lucide-react";
import { motion } from "framer-motion";

const recommendations = [
  {
    product: "MacBook Pro M4",
    stock: 8,
    demand: 42,
    recommended: 40,
    priority: "Critical",
  },
  {
    product: "iPhone 16 Pro",
    stock: 15,
    demand: 36,
    recommended: 30,
    priority: "High",
  },
  {
    product: "AirPods Pro",
    stock: 28,
    demand: 32,
    recommended: 18,
    priority: "Medium",
  },
];

export default function RestockRecommendations() {
  return (
    <section>
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-white">
          AI Restock Recommendations
        </h2>

        <p className="text-slate-400">
          Smart inventory suggestions generated by GrowthPilot AI
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {recommendations.map((item) => (
          <motion.div
            key={item.product}
            whileHover={{ y: -6, scale: 1.02 }}
            transition={{ duration: 0.25 }}
            className="rounded-3xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-950 p-6 shadow-xl"
          >
            <div className="flex items-center justify-between">

              <div className="rounded-2xl bg-cyan-500/20 p-3">
                <Package
                  size={28}
                  className="text-cyan-400"
                />
              </div>

              <span
                className={`rounded-full px-3 py-1 text-sm font-semibold ${
                  item.priority === "Critical"
                    ? "bg-red-500/20 text-red-400"
                    : item.priority === "High"
                    ? "bg-amber-500/20 text-amber-400"
                    : "bg-emerald-500/20 text-emerald-400"
                }`}
              >
                {item.priority}
              </span>
            </div>

            <h3 className="mt-5 text-xl font-bold text-white">
              {item.product}
            </h3>

            <div className="mt-6 space-y-4">

              <div className="flex justify-between">
                <span className="text-slate-400">
                  Current Stock
                </span>

                <span className="font-semibold text-white">
                  {item.stock}
                </span>
              </div>

              <div className="flex justify-between">
                <span className="text-slate-400">
                  Predicted Demand
                </span>

                <span className="font-semibold text-cyan-400">
                  {item.demand}
                </span>
              </div>

              <div className="flex justify-between">
                <span className="text-slate-400">
                  Suggested Order
                </span>

                <span className="font-semibold text-indigo-400">
                  {item.recommended}
                </span>
              </div>

            </div>

            <button className="mt-8 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-cyan-500 to-indigo-600 py-3 font-semibold text-white transition hover:scale-[1.02]">
              <TrendingUp size={18} />
              Generate Purchase Order
            </button>
          </motion.div>
        ))}
      </div>

      <div className="mt-8 rounded-2xl border border-amber-500/20 bg-amber-500/10 p-5">
        <div className="flex items-center gap-3">
          <AlertTriangle className="text-amber-400" />

          <div>
            <h3 className="font-semibold text-amber-300">
              AI Inventory Warning
            </h3>

            <p className="mt-1 text-slate-300">
              Demand for premium electronics is expected to increase by
              approximately <strong>18%</strong> next month. Consider
              replenishing stock early to avoid shortages.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}